//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.312.
// 
namespace Omni.Client.org.omniproject.service {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OmniServiceSoap", Namespace="http://service.omniproject.org/")]
    public partial class OmniService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public OmniService() {
            this.Url = "http://service.omniproject.org/service/omniservice.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/SessionNew", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid SessionNew() {
            object[] results = this.Invoke("SessionNew", new object[0]);
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSessionNew(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SessionNew", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Guid EndSessionNew(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/SessionExists", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SessionExists(System.Guid session) {
            object[] results = this.Invoke("SessionExists", new object[] {
                        session});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSessionExists(System.Guid session, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SessionExists", new object[] {
                        session}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndSessionExists(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/SessionAbandon", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SessionAbandon(System.Guid session) {
            this.Invoke("SessionAbandon", new object[] {
                        session});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSessionAbandon(System.Guid session, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SessionAbandon", new object[] {
                        session}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSessionAbandon(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/SessionKeepAlive", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SessionKeepAlive(System.Guid session) {
            this.Invoke("SessionKeepAlive", new object[] {
                        session});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSessionKeepAlive(System.Guid session, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SessionKeepAlive", new object[] {
                        session}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSessionKeepAlive(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserGetCaptcha", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] UserGetCaptcha(System.Guid session, int width, int height, string bgcolor, string frontcolor) {
            object[] results = this.Invoke("UserGetCaptcha", new object[] {
                        session,
                        width,
                        height,
                        bgcolor,
                        frontcolor});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserGetCaptcha(System.Guid session, int width, int height, string bgcolor, string frontcolor, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserGetCaptcha", new object[] {
                        session,
                        width,
                        height,
                        bgcolor,
                        frontcolor}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndUserGetCaptcha(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserIsLoggedIn", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UserIsLoggedIn(System.Guid session) {
            object[] results = this.Invoke("UserIsLoggedIn", new object[] {
                        session});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserIsLoggedIn(System.Guid session, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserIsLoggedIn", new object[] {
                        session}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndUserIsLoggedIn(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserLogin", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UserLogin(string username, string md5password, string captcha, System.Guid session) {
            object[] results = this.Invoke("UserLogin", new object[] {
                        username,
                        md5password,
                        captcha,
                        session});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserLogin(string username, string md5password, string captcha, System.Guid session, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserLogin", new object[] {
                        username,
                        md5password,
                        captcha,
                        session}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndUserLogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserLogout", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UserLogout(System.Guid session) {
            this.Invoke("UserLogout", new object[] {
                        session});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserLogout(System.Guid session, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserLogout", new object[] {
                        session}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUserLogout(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserRegister", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UserRegister(string username, string md5password, string name, string email, string captcha, System.Guid session) {
            object[] results = this.Invoke("UserRegister", new object[] {
                        username,
                        md5password,
                        name,
                        email,
                        captcha,
                        session});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserRegister(string username, string md5password, string name, string email, string captcha, System.Guid session, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserRegister", new object[] {
                        username,
                        md5password,
                        name,
                        email,
                        captcha,
                        session}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndUserRegister(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserCurrent", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User UserCurrent(System.Guid session) {
            object[] results = this.Invoke("UserCurrent", new object[] {
                        session});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserCurrent(System.Guid session, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserCurrent", new object[] {
                        session}, callback, asyncState);
        }
        
        /// <remarks/>
        public User EndUserCurrent(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/DefinitionLookup", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DefinitionLookup(string lang, string word) {
            object[] results = this.Invoke("DefinitionLookup", new object[] {
                        lang,
                        word});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDefinitionLookup(string lang, string word, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DefinitionLookup", new object[] {
                        lang,
                        word}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndDefinitionLookup(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/TranslationLookup", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TranslationLookup(string src_lang, string dst_lang, string message) {
            object[] results = this.Invoke("TranslationLookup", new object[] {
                        src_lang,
                        dst_lang,
                        message});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTranslationLookup(string src_lang, string dst_lang, string message, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TranslationLookup", new object[] {
                        src_lang,
                        dst_lang,
                        message}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndTranslationLookup(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.omniproject.org/")]
    public partial class User {
        
        private string nameField;
        
        private string usernameField;
        
        private string emailField;
        
        private int idField;
        
        private string descriptionField;
        
        private System.DateTime reg_dateField;
        
        private System.DateTime log_dateField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime reg_date {
            get {
                return this.reg_dateField;
            }
            set {
                this.reg_dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime log_date {
            get {
                return this.log_dateField;
            }
            set {
                this.log_dateField = value;
            }
        }
    }
}
