//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.312.
// 
#pragma warning disable 1591

namespace Omni.Client.org.omniproject.service {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OmniServiceSoap", Namespace="http://service.omniproject.org/")]
    public partial class OmniService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SessionNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback SessionExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SessionAbandonOperationCompleted;
        
        private System.Threading.SendOrPostCallback SessionKeepAliveOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserGetCaptchaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserIsLoggedInOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserLogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserRegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserCurrentOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserInterestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback InterestListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DefinitionLookupOperationCompleted;
        
        private System.Threading.SendOrPostCallback TranslationLookupOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OmniService() {
            this.Url = global::Omni.Client.Properties.Settings.Default.Omni_Client_org_omniproject_service_OmniService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SessionNewCompletedEventHandler SessionNewCompleted;
        
        /// <remarks/>
        public event SessionExistsCompletedEventHandler SessionExistsCompleted;
        
        /// <remarks/>
        public event SessionAbandonCompletedEventHandler SessionAbandonCompleted;
        
        /// <remarks/>
        public event SessionKeepAliveCompletedEventHandler SessionKeepAliveCompleted;
        
        /// <remarks/>
        public event UserGetCaptchaCompletedEventHandler UserGetCaptchaCompleted;
        
        /// <remarks/>
        public event UserIsLoggedInCompletedEventHandler UserIsLoggedInCompleted;
        
        /// <remarks/>
        public event UserLoginCompletedEventHandler UserLoginCompleted;
        
        /// <remarks/>
        public event UserLogoutCompletedEventHandler UserLogoutCompleted;
        
        /// <remarks/>
        public event UserRegisterCompletedEventHandler UserRegisterCompleted;
        
        /// <remarks/>
        public event UserUpdateCompletedEventHandler UserUpdateCompleted;
        
        /// <remarks/>
        public event UserCurrentCompletedEventHandler UserCurrentCompleted;
        
        /// <remarks/>
        public event UserInterestsCompletedEventHandler UserInterestsCompleted;
        
        /// <remarks/>
        public event InterestListCompletedEventHandler InterestListCompleted;
        
        /// <remarks/>
        public event DefinitionLookupCompletedEventHandler DefinitionLookupCompleted;
        
        /// <remarks/>
        public event TranslationLookupCompletedEventHandler TranslationLookupCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/SessionNew", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid SessionNew() {
            object[] results = this.Invoke("SessionNew", new object[0]);
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public void SessionNewAsync() {
            this.SessionNewAsync(null);
        }
        
        /// <remarks/>
        public void SessionNewAsync(object userState) {
            if ((this.SessionNewOperationCompleted == null)) {
                this.SessionNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSessionNewOperationCompleted);
            }
            this.InvokeAsync("SessionNew", new object[0], this.SessionNewOperationCompleted, userState);
        }
        
        private void OnSessionNewOperationCompleted(object arg) {
            if ((this.SessionNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SessionNewCompleted(this, new SessionNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/SessionExists", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SessionExists(System.Guid session) {
            object[] results = this.Invoke("SessionExists", new object[] {
                        session});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SessionExistsAsync(System.Guid session) {
            this.SessionExistsAsync(session, null);
        }
        
        /// <remarks/>
        public void SessionExistsAsync(System.Guid session, object userState) {
            if ((this.SessionExistsOperationCompleted == null)) {
                this.SessionExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSessionExistsOperationCompleted);
            }
            this.InvokeAsync("SessionExists", new object[] {
                        session}, this.SessionExistsOperationCompleted, userState);
        }
        
        private void OnSessionExistsOperationCompleted(object arg) {
            if ((this.SessionExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SessionExistsCompleted(this, new SessionExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/SessionAbandon", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SessionAbandon(System.Guid session) {
            this.Invoke("SessionAbandon", new object[] {
                        session});
        }
        
        /// <remarks/>
        public void SessionAbandonAsync(System.Guid session) {
            this.SessionAbandonAsync(session, null);
        }
        
        /// <remarks/>
        public void SessionAbandonAsync(System.Guid session, object userState) {
            if ((this.SessionAbandonOperationCompleted == null)) {
                this.SessionAbandonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSessionAbandonOperationCompleted);
            }
            this.InvokeAsync("SessionAbandon", new object[] {
                        session}, this.SessionAbandonOperationCompleted, userState);
        }
        
        private void OnSessionAbandonOperationCompleted(object arg) {
            if ((this.SessionAbandonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SessionAbandonCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/SessionKeepAlive", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SessionKeepAlive(System.Guid session) {
            this.Invoke("SessionKeepAlive", new object[] {
                        session});
        }
        
        /// <remarks/>
        public void SessionKeepAliveAsync(System.Guid session) {
            this.SessionKeepAliveAsync(session, null);
        }
        
        /// <remarks/>
        public void SessionKeepAliveAsync(System.Guid session, object userState) {
            if ((this.SessionKeepAliveOperationCompleted == null)) {
                this.SessionKeepAliveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSessionKeepAliveOperationCompleted);
            }
            this.InvokeAsync("SessionKeepAlive", new object[] {
                        session}, this.SessionKeepAliveOperationCompleted, userState);
        }
        
        private void OnSessionKeepAliveOperationCompleted(object arg) {
            if ((this.SessionKeepAliveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SessionKeepAliveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserGetCaptcha", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] UserGetCaptcha(System.Guid session, int width, int height, string bgcolor, string frontcolor) {
            object[] results = this.Invoke("UserGetCaptcha", new object[] {
                        session,
                        width,
                        height,
                        bgcolor,
                        frontcolor});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void UserGetCaptchaAsync(System.Guid session, int width, int height, string bgcolor, string frontcolor) {
            this.UserGetCaptchaAsync(session, width, height, bgcolor, frontcolor, null);
        }
        
        /// <remarks/>
        public void UserGetCaptchaAsync(System.Guid session, int width, int height, string bgcolor, string frontcolor, object userState) {
            if ((this.UserGetCaptchaOperationCompleted == null)) {
                this.UserGetCaptchaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserGetCaptchaOperationCompleted);
            }
            this.InvokeAsync("UserGetCaptcha", new object[] {
                        session,
                        width,
                        height,
                        bgcolor,
                        frontcolor}, this.UserGetCaptchaOperationCompleted, userState);
        }
        
        private void OnUserGetCaptchaOperationCompleted(object arg) {
            if ((this.UserGetCaptchaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserGetCaptchaCompleted(this, new UserGetCaptchaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserIsLoggedIn", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UserIsLoggedIn(System.Guid session) {
            object[] results = this.Invoke("UserIsLoggedIn", new object[] {
                        session});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UserIsLoggedInAsync(System.Guid session) {
            this.UserIsLoggedInAsync(session, null);
        }
        
        /// <remarks/>
        public void UserIsLoggedInAsync(System.Guid session, object userState) {
            if ((this.UserIsLoggedInOperationCompleted == null)) {
                this.UserIsLoggedInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserIsLoggedInOperationCompleted);
            }
            this.InvokeAsync("UserIsLoggedIn", new object[] {
                        session}, this.UserIsLoggedInOperationCompleted, userState);
        }
        
        private void OnUserIsLoggedInOperationCompleted(object arg) {
            if ((this.UserIsLoggedInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserIsLoggedInCompleted(this, new UserIsLoggedInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserLogin", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UserLogin(string username, string md5password, System.Guid session) {
            object[] results = this.Invoke("UserLogin", new object[] {
                        username,
                        md5password,
                        session});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UserLoginAsync(string username, string md5password, System.Guid session) {
            this.UserLoginAsync(username, md5password, session, null);
        }
        
        /// <remarks/>
        public void UserLoginAsync(string username, string md5password, System.Guid session, object userState) {
            if ((this.UserLoginOperationCompleted == null)) {
                this.UserLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserLoginOperationCompleted);
            }
            this.InvokeAsync("UserLogin", new object[] {
                        username,
                        md5password,
                        session}, this.UserLoginOperationCompleted, userState);
        }
        
        private void OnUserLoginOperationCompleted(object arg) {
            if ((this.UserLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserLoginCompleted(this, new UserLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserLogout", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UserLogout(System.Guid session) {
            this.Invoke("UserLogout", new object[] {
                        session});
        }
        
        /// <remarks/>
        public void UserLogoutAsync(System.Guid session) {
            this.UserLogoutAsync(session, null);
        }
        
        /// <remarks/>
        public void UserLogoutAsync(System.Guid session, object userState) {
            if ((this.UserLogoutOperationCompleted == null)) {
                this.UserLogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserLogoutOperationCompleted);
            }
            this.InvokeAsync("UserLogout", new object[] {
                        session}, this.UserLogoutOperationCompleted, userState);
        }
        
        private void OnUserLogoutOperationCompleted(object arg) {
            if ((this.UserLogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserLogoutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserRegister", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UserRegister(string username, string md5password, string name, string email, string captcha, System.Guid session) {
            object[] results = this.Invoke("UserRegister", new object[] {
                        username,
                        md5password,
                        name,
                        email,
                        captcha,
                        session});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UserRegisterAsync(string username, string md5password, string name, string email, string captcha, System.Guid session) {
            this.UserRegisterAsync(username, md5password, name, email, captcha, session, null);
        }
        
        /// <remarks/>
        public void UserRegisterAsync(string username, string md5password, string name, string email, string captcha, System.Guid session, object userState) {
            if ((this.UserRegisterOperationCompleted == null)) {
                this.UserRegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserRegisterOperationCompleted);
            }
            this.InvokeAsync("UserRegister", new object[] {
                        username,
                        md5password,
                        name,
                        email,
                        captcha,
                        session}, this.UserRegisterOperationCompleted, userState);
        }
        
        private void OnUserRegisterOperationCompleted(object arg) {
            if ((this.UserRegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserRegisterCompleted(this, new UserRegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserUpdate", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UserUpdate(string name, string email, string description, string sn_network, string sn_screenname, System.Guid session) {
            object[] results = this.Invoke("UserUpdate", new object[] {
                        name,
                        email,
                        description,
                        sn_network,
                        sn_screenname,
                        session});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UserUpdateAsync(string name, string email, string description, string sn_network, string sn_screenname, System.Guid session) {
            this.UserUpdateAsync(name, email, description, sn_network, sn_screenname, session, null);
        }
        
        /// <remarks/>
        public void UserUpdateAsync(string name, string email, string description, string sn_network, string sn_screenname, System.Guid session, object userState) {
            if ((this.UserUpdateOperationCompleted == null)) {
                this.UserUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserUpdateOperationCompleted);
            }
            this.InvokeAsync("UserUpdate", new object[] {
                        name,
                        email,
                        description,
                        sn_network,
                        sn_screenname,
                        session}, this.UserUpdateOperationCompleted, userState);
        }
        
        private void OnUserUpdateOperationCompleted(object arg) {
            if ((this.UserUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserUpdateCompleted(this, new UserUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserCurrent", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User UserCurrent(System.Guid session) {
            object[] results = this.Invoke("UserCurrent", new object[] {
                        session});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void UserCurrentAsync(System.Guid session) {
            this.UserCurrentAsync(session, null);
        }
        
        /// <remarks/>
        public void UserCurrentAsync(System.Guid session, object userState) {
            if ((this.UserCurrentOperationCompleted == null)) {
                this.UserCurrentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserCurrentOperationCompleted);
            }
            this.InvokeAsync("UserCurrent", new object[] {
                        session}, this.UserCurrentOperationCompleted, userState);
        }
        
        private void OnUserCurrentOperationCompleted(object arg) {
            if ((this.UserCurrentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserCurrentCompleted(this, new UserCurrentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserInterests", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Interest[] UserInterests(int id, System.Guid session) {
            object[] results = this.Invoke("UserInterests", new object[] {
                        id,
                        session});
            return ((Interest[])(results[0]));
        }
        
        /// <remarks/>
        public void UserInterestsAsync(int id, System.Guid session) {
            this.UserInterestsAsync(id, session, null);
        }
        
        /// <remarks/>
        public void UserInterestsAsync(int id, System.Guid session, object userState) {
            if ((this.UserInterestsOperationCompleted == null)) {
                this.UserInterestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserInterestsOperationCompleted);
            }
            this.InvokeAsync("UserInterests", new object[] {
                        id,
                        session}, this.UserInterestsOperationCompleted, userState);
        }
        
        private void OnUserInterestsOperationCompleted(object arg) {
            if ((this.UserInterestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserInterestsCompleted(this, new UserInterestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/InterestList", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Interest[] InterestList(System.Guid session) {
            object[] results = this.Invoke("InterestList", new object[] {
                        session});
            return ((Interest[])(results[0]));
        }
        
        /// <remarks/>
        public void InterestListAsync(System.Guid session) {
            this.InterestListAsync(session, null);
        }
        
        /// <remarks/>
        public void InterestListAsync(System.Guid session, object userState) {
            if ((this.InterestListOperationCompleted == null)) {
                this.InterestListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInterestListOperationCompleted);
            }
            this.InvokeAsync("InterestList", new object[] {
                        session}, this.InterestListOperationCompleted, userState);
        }
        
        private void OnInterestListOperationCompleted(object arg) {
            if ((this.InterestListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InterestListCompleted(this, new InterestListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/DefinitionLookup", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DefinitionLookup(string lang, string word) {
            object[] results = this.Invoke("DefinitionLookup", new object[] {
                        lang,
                        word});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DefinitionLookupAsync(string lang, string word) {
            this.DefinitionLookupAsync(lang, word, null);
        }
        
        /// <remarks/>
        public void DefinitionLookupAsync(string lang, string word, object userState) {
            if ((this.DefinitionLookupOperationCompleted == null)) {
                this.DefinitionLookupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDefinitionLookupOperationCompleted);
            }
            this.InvokeAsync("DefinitionLookup", new object[] {
                        lang,
                        word}, this.DefinitionLookupOperationCompleted, userState);
        }
        
        private void OnDefinitionLookupOperationCompleted(object arg) {
            if ((this.DefinitionLookupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DefinitionLookupCompleted(this, new DefinitionLookupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/TranslationLookup", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TranslationLookup(string src_lang, string dst_lang, string message) {
            object[] results = this.Invoke("TranslationLookup", new object[] {
                        src_lang,
                        dst_lang,
                        message});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TranslationLookupAsync(string src_lang, string dst_lang, string message) {
            this.TranslationLookupAsync(src_lang, dst_lang, message, null);
        }
        
        /// <remarks/>
        public void TranslationLookupAsync(string src_lang, string dst_lang, string message, object userState) {
            if ((this.TranslationLookupOperationCompleted == null)) {
                this.TranslationLookupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTranslationLookupOperationCompleted);
            }
            this.InvokeAsync("TranslationLookup", new object[] {
                        src_lang,
                        dst_lang,
                        message}, this.TranslationLookupOperationCompleted, userState);
        }
        
        private void OnTranslationLookupOperationCompleted(object arg) {
            if ((this.TranslationLookupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TranslationLookupCompleted(this, new TranslationLookupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.omniproject.org/")]
    public partial class User {
        
        private string nameField;
        
        private string usernameField;
        
        private string emailField;
        
        private int idField;
        
        private string descriptionField;
        
        private string sn_networkField;
        
        private string sn_screennameField;
        
        private System.DateTime reg_dateField;
        
        private System.DateTime log_dateField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string sn_network {
            get {
                return this.sn_networkField;
            }
            set {
                this.sn_networkField = value;
            }
        }
        
        /// <remarks/>
        public string sn_screenname {
            get {
                return this.sn_screennameField;
            }
            set {
                this.sn_screennameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime reg_date {
            get {
                return this.reg_dateField;
            }
            set {
                this.reg_dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime log_date {
            get {
                return this.log_dateField;
            }
            set {
                this.log_dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.omniproject.org/")]
    public partial class Interest {
        
        private int idField;
        
        private int parent_idField;
        
        private string nameField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int parent_id {
            get {
                return this.parent_idField;
            }
            set {
                this.parent_idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void SessionNewCompletedEventHandler(object sender, SessionNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SessionNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SessionNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Guid Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void SessionExistsCompletedEventHandler(object sender, SessionExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SessionExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SessionExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void SessionAbandonCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void SessionKeepAliveCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserGetCaptchaCompletedEventHandler(object sender, UserGetCaptchaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserGetCaptchaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserGetCaptchaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserIsLoggedInCompletedEventHandler(object sender, UserIsLoggedInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserIsLoggedInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserIsLoggedInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserLoginCompletedEventHandler(object sender, UserLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserLogoutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserRegisterCompletedEventHandler(object sender, UserRegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserRegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserRegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserUpdateCompletedEventHandler(object sender, UserUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserCurrentCompletedEventHandler(object sender, UserCurrentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserCurrentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserCurrentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserInterestsCompletedEventHandler(object sender, UserInterestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserInterestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserInterestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Interest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Interest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void InterestListCompletedEventHandler(object sender, InterestListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InterestListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InterestListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Interest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Interest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void DefinitionLookupCompletedEventHandler(object sender, DefinitionLookupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DefinitionLookupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DefinitionLookupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void TranslationLookupCompletedEventHandler(object sender, TranslationLookupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TranslationLookupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TranslationLookupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591