//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.312.
// 
#pragma warning disable 1591

namespace Omni.Client.org.omniproject.service {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OmniServiceSoap", Namespace="http://service.omniproject.org/")]
    public partial class OmniService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SessionNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback SessionExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SessionAbandonOperationCompleted;
        
        private System.Threading.SendOrPostCallback SessionKeepAliveOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserGetCaptchaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserIsLoggedInOperationCompleted;
        
        private System.Threading.SendOrPostCallback DefinitionLookupOperationCompleted;
        
        private System.Threading.SendOrPostCallback TranslationLookupOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OmniService() {
            this.Url = global::Omni.Client.Properties.Settings.Default.Omni_Client_org_omniproject_service_OmniService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SessionNewCompletedEventHandler SessionNewCompleted;
        
        /// <remarks/>
        public event SessionExistsCompletedEventHandler SessionExistsCompleted;
        
        /// <remarks/>
        public event SessionAbandonCompletedEventHandler SessionAbandonCompleted;
        
        /// <remarks/>
        public event SessionKeepAliveCompletedEventHandler SessionKeepAliveCompleted;
        
        /// <remarks/>
        public event UserGetCaptchaCompletedEventHandler UserGetCaptchaCompleted;
        
        /// <remarks/>
        public event UserIsLoggedInCompletedEventHandler UserIsLoggedInCompleted;
        
        /// <remarks/>
        public event DefinitionLookupCompletedEventHandler DefinitionLookupCompleted;
        
        /// <remarks/>
        public event TranslationLookupCompletedEventHandler TranslationLookupCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/SessionNew", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid SessionNew() {
            object[] results = this.Invoke("SessionNew", new object[0]);
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public void SessionNewAsync() {
            this.SessionNewAsync(null);
        }
        
        /// <remarks/>
        public void SessionNewAsync(object userState) {
            if ((this.SessionNewOperationCompleted == null)) {
                this.SessionNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSessionNewOperationCompleted);
            }
            this.InvokeAsync("SessionNew", new object[0], this.SessionNewOperationCompleted, userState);
        }
        
        private void OnSessionNewOperationCompleted(object arg) {
            if ((this.SessionNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SessionNewCompleted(this, new SessionNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/SessionExists", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SessionExists(System.Guid session) {
            object[] results = this.Invoke("SessionExists", new object[] {
                        session});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SessionExistsAsync(System.Guid session) {
            this.SessionExistsAsync(session, null);
        }
        
        /// <remarks/>
        public void SessionExistsAsync(System.Guid session, object userState) {
            if ((this.SessionExistsOperationCompleted == null)) {
                this.SessionExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSessionExistsOperationCompleted);
            }
            this.InvokeAsync("SessionExists", new object[] {
                        session}, this.SessionExistsOperationCompleted, userState);
        }
        
        private void OnSessionExistsOperationCompleted(object arg) {
            if ((this.SessionExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SessionExistsCompleted(this, new SessionExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/SessionAbandon", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SessionAbandon(System.Guid session) {
            this.Invoke("SessionAbandon", new object[] {
                        session});
        }
        
        /// <remarks/>
        public void SessionAbandonAsync(System.Guid session) {
            this.SessionAbandonAsync(session, null);
        }
        
        /// <remarks/>
        public void SessionAbandonAsync(System.Guid session, object userState) {
            if ((this.SessionAbandonOperationCompleted == null)) {
                this.SessionAbandonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSessionAbandonOperationCompleted);
            }
            this.InvokeAsync("SessionAbandon", new object[] {
                        session}, this.SessionAbandonOperationCompleted, userState);
        }
        
        private void OnSessionAbandonOperationCompleted(object arg) {
            if ((this.SessionAbandonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SessionAbandonCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/SessionKeepAlive", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SessionKeepAlive(System.Guid session) {
            this.Invoke("SessionKeepAlive", new object[] {
                        session});
        }
        
        /// <remarks/>
        public void SessionKeepAliveAsync(System.Guid session) {
            this.SessionKeepAliveAsync(session, null);
        }
        
        /// <remarks/>
        public void SessionKeepAliveAsync(System.Guid session, object userState) {
            if ((this.SessionKeepAliveOperationCompleted == null)) {
                this.SessionKeepAliveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSessionKeepAliveOperationCompleted);
            }
            this.InvokeAsync("SessionKeepAlive", new object[] {
                        session}, this.SessionKeepAliveOperationCompleted, userState);
        }
        
        private void OnSessionKeepAliveOperationCompleted(object arg) {
            if ((this.SessionKeepAliveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SessionKeepAliveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserGetCaptcha", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] UserGetCaptcha(System.Guid session, int width, int height, string bgcolor, string frontcolor) {
            object[] results = this.Invoke("UserGetCaptcha", new object[] {
                        session,
                        width,
                        height,
                        bgcolor,
                        frontcolor});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void UserGetCaptchaAsync(System.Guid session, int width, int height, string bgcolor, string frontcolor) {
            this.UserGetCaptchaAsync(session, width, height, bgcolor, frontcolor, null);
        }
        
        /// <remarks/>
        public void UserGetCaptchaAsync(System.Guid session, int width, int height, string bgcolor, string frontcolor, object userState) {
            if ((this.UserGetCaptchaOperationCompleted == null)) {
                this.UserGetCaptchaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserGetCaptchaOperationCompleted);
            }
            this.InvokeAsync("UserGetCaptcha", new object[] {
                        session,
                        width,
                        height,
                        bgcolor,
                        frontcolor}, this.UserGetCaptchaOperationCompleted, userState);
        }
        
        private void OnUserGetCaptchaOperationCompleted(object arg) {
            if ((this.UserGetCaptchaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserGetCaptchaCompleted(this, new UserGetCaptchaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/UserIsLoggedIn", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UserIsLoggedIn(System.Guid session) {
            object[] results = this.Invoke("UserIsLoggedIn", new object[] {
                        session});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UserIsLoggedInAsync(System.Guid session) {
            this.UserIsLoggedInAsync(session, null);
        }
        
        /// <remarks/>
        public void UserIsLoggedInAsync(System.Guid session, object userState) {
            if ((this.UserIsLoggedInOperationCompleted == null)) {
                this.UserIsLoggedInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserIsLoggedInOperationCompleted);
            }
            this.InvokeAsync("UserIsLoggedIn", new object[] {
                        session}, this.UserIsLoggedInOperationCompleted, userState);
        }
        
        private void OnUserIsLoggedInOperationCompleted(object arg) {
            if ((this.UserIsLoggedInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserIsLoggedInCompleted(this, new UserIsLoggedInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/DefinitionLookup", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DefinitionLookup(int lang_id, string word) {
            object[] results = this.Invoke("DefinitionLookup", new object[] {
                        lang_id,
                        word});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DefinitionLookupAsync(int lang_id, string word) {
            this.DefinitionLookupAsync(lang_id, word, null);
        }
        
        /// <remarks/>
        public void DefinitionLookupAsync(int lang_id, string word, object userState) {
            if ((this.DefinitionLookupOperationCompleted == null)) {
                this.DefinitionLookupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDefinitionLookupOperationCompleted);
            }
            this.InvokeAsync("DefinitionLookup", new object[] {
                        lang_id,
                        word}, this.DefinitionLookupOperationCompleted, userState);
        }
        
        private void OnDefinitionLookupOperationCompleted(object arg) {
            if ((this.DefinitionLookupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DefinitionLookupCompleted(this, new DefinitionLookupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.omniproject.org/TranslationLookup", RequestNamespace="http://service.omniproject.org/", ResponseNamespace="http://service.omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TranslationLookup(int src_lang_id, int dst_lang_id, string message) {
            object[] results = this.Invoke("TranslationLookup", new object[] {
                        src_lang_id,
                        dst_lang_id,
                        message});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TranslationLookupAsync(int src_lang_id, int dst_lang_id, string message) {
            this.TranslationLookupAsync(src_lang_id, dst_lang_id, message, null);
        }
        
        /// <remarks/>
        public void TranslationLookupAsync(int src_lang_id, int dst_lang_id, string message, object userState) {
            if ((this.TranslationLookupOperationCompleted == null)) {
                this.TranslationLookupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTranslationLookupOperationCompleted);
            }
            this.InvokeAsync("TranslationLookup", new object[] {
                        src_lang_id,
                        dst_lang_id,
                        message}, this.TranslationLookupOperationCompleted, userState);
        }
        
        private void OnTranslationLookupOperationCompleted(object arg) {
            if ((this.TranslationLookupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TranslationLookupCompleted(this, new TranslationLookupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void SessionNewCompletedEventHandler(object sender, SessionNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SessionNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SessionNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Guid Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void SessionExistsCompletedEventHandler(object sender, SessionExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SessionExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SessionExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void SessionAbandonCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void SessionKeepAliveCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserGetCaptchaCompletedEventHandler(object sender, UserGetCaptchaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserGetCaptchaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserGetCaptchaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserIsLoggedInCompletedEventHandler(object sender, UserIsLoggedInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserIsLoggedInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserIsLoggedInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void DefinitionLookupCompletedEventHandler(object sender, DefinitionLookupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DefinitionLookupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DefinitionLookupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void TranslationLookupCompletedEventHandler(object sender, TranslationLookupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TranslationLookupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TranslationLookupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591