SET IDENTITY_INSERT obj_interest ON
GO
INSERT obj_interest(parent_id,name) VALUES('1','0','Music')
INSERT obj_interest(parent_id,name) VALUES('2','0','Movies')
INSERT obj_interest(parent_id,name) VALUES('3','0','Sports')
INSERT obj_interest(parent_id,name) VALUES('4','0','TV')
INSERT obj_interest(parent_id,name) VALUES('5','0','Technology')
INSERT obj_interest(parent_id,name) VALUES('6','1','MusicRockPop')
INSERT obj_interest(parent_id,name) VALUES('7','1','MusicRap')
INSERT obj_interest(parent_id,name) VALUES('8','1','MusicTechnoDance')
INSERT obj_interest(parent_id,name) VALUES('9','1','MusicCountry')
INSERT obj_interest(parent_id,name) VALUES('10','1','MusicClassical')
INSERT obj_interest(parent_id,name) VALUES('11','1','MusicOldies')
INSERT obj_interest(parent_id,name) VALUES('12','2','MoviesAction')
INSERT obj_interest(parent_id,name) VALUES('13','2','MoviesComedy')
INSERT obj_interest(parent_id,name) VALUES('14','2','MoviesHorror')
INSERT obj_interest(parent_id,name) VALUES('15','2','MoviesRomance')
INSERT obj_interest(parent_id,name) VALUES('16','2','MoviesIndependent')
INSERT obj_interest(parent_id,name) VALUES('17','2','MoviesDocumentary')
INSERT obj_interest(parent_id,name) VALUES('18','2','MoviesMusical')
INSERT obj_interest(parent_id,name) VALUES('19','3','SportsSoccer')
INSERT obj_interest(parent_id,name) VALUES('20','3','SportsBaseball')
INSERT obj_interest(parent_id,name) VALUES('21','3','SportsRugby')
INSERT obj_interest(parent_id,name) VALUES('22','3','SportsFootball')
INSERT obj_interest(parent_id,name) VALUES('23','3','SportsDodgeball')
INSERT obj_interest(parent_id,name) VALUES('24','3','SportsGolf')
INSERT obj_interest(parent_id,name) VALUES('25','3','SportsTrackField')
INSERT obj_interest(parent_id,name) VALUES('26','3','SportsSwimming')
INSERT obj_interest(parent_id,name) VALUES('27','3','SportsVolleyball')
INSERT obj_interest(parent_id,name) VALUES('28','4','TVDrama')
INSERT obj_interest(parent_id,name) VALUES('29','4','TVCrime')
INSERT obj_interest(parent_id,name) VALUES('30','4','TVComedy')
INSERT obj_interest(parent_id,name) VALUES('31','4','TVNewShows')
INSERT obj_interest(parent_id,name) VALUES('32','4','TVOldShows')
INSERT obj_interest(parent_id,name) VALUES('33','5','TechComputerProgramming')
INSERT obj_interest(parent_id,name) VALUES('34','5','TechVideoEditing')
INSERT obj_interest(parent_id,name) VALUES('35','5','TechVideoGames')
INSERT obj_interest(parent_id,name) VALUES('36','0','Cheese')
INSERT obj_interest(parent_id,name) VALUES('37','36','CheeseCheddar')
INSERT obj_interest(parent_id,name) VALUES('38','36','CheesePepperjack')
INSERT obj_interest(parent_id,name) VALUES('39','36','CheeseProvolone')
INSERT obj_interest(parent_id,name) VALUES('40','36','CheeseAmerican')
INSERT obj_interest(parent_id,name) VALUES('41','36','CheeseParmesan')
INSERT obj_interest(parent_id,name) VALUES('42','36','CheeseMozzarella')
INSERT obj_interest(parent_id,name) VALUES('43','3','SportsBasketball')
SET IDENTITY_INSERT obj_interest OFF
GO
SET IDENTITY_INSERT obj_lang ON
GO
INSERT obj_lang(code) VALUES('1','en-US')
INSERT obj_lang(code) VALUES('2','zh-CN')
INSERT obj_lang(code) VALUES('3','ko')
INSERT obj_lang(code) VALUES('4','es')
INSERT obj_lang(code) VALUES('5','de')
INSERT obj_lang(code) VALUES('6','ja')
INSERT obj_lang(code) VALUES('7','fr')
INSERT obj_lang(code) VALUES('8','pt')
INSERT obj_lang(code) VALUES('9','ru')
INSERT obj_lang(code) VALUES('10','it')
SET IDENTITY_INSERT obj_lang OFF
GO
