//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.312.
// 
#pragma warning disable 1591

namespace Omni.Web.org.omniproject {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://omniproject.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InitializeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserCaptchaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserRegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserAuthorizeByUsernameOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserIsLoggedInOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserLogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserCurrentOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserUpdateByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserPasswordUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserIdGetByUsernameOperationCompleted;
        
        private System.Threading.SendOrPostCallback DictionaryLookupOperationCompleted;
        
        private System.Threading.SendOrPostCallback TranslationLookupOperationCompleted;
        
        private System.Threading.SendOrPostCallback LanguageListOperationCompleted;
        
        private System.Threading.SendOrPostCallback LanguageNameQueryByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserLanguageListByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserLanguageSetByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserLanguageDeleteByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback InterestListOperationCompleted;
        
        private System.Threading.SendOrPostCallback InterestLangListOperationCompleted;
        
        private System.Threading.SendOrPostCallback InterestNameQueryByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserInterestListOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserInterestAddByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserInterestDeleteByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransAnsRateByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback MessageSendOperationCompleted;
        
        private System.Threading.SendOrPostCallback MessageRecvByUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::Omni.Web.Properties.Settings.Default.Omni_Web_org_omniproject_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InitializeCompletedEventHandler InitializeCompleted;
        
        /// <remarks/>
        public event UserCaptchaCompletedEventHandler UserCaptchaCompleted;
        
        /// <remarks/>
        public event UserRegisterCompletedEventHandler UserRegisterCompleted;
        
        /// <remarks/>
        public event UserAuthorizeByUsernameCompletedEventHandler UserAuthorizeByUsernameCompleted;
        
        /// <remarks/>
        public event UserIsLoggedInCompletedEventHandler UserIsLoggedInCompleted;
        
        /// <remarks/>
        public event UserLogoutCompletedEventHandler UserLogoutCompleted;
        
        /// <remarks/>
        public event UserCurrentCompletedEventHandler UserCurrentCompleted;
        
        /// <remarks/>
        public event UserUpdateByIdCompletedEventHandler UserUpdateByIdCompleted;
        
        /// <remarks/>
        public event UserPasswordUpdateCompletedEventHandler UserPasswordUpdateCompleted;
        
        /// <remarks/>
        public event UserIdGetByUsernameCompletedEventHandler UserIdGetByUsernameCompleted;
        
        /// <remarks/>
        public event DictionaryLookupCompletedEventHandler DictionaryLookupCompleted;
        
        /// <remarks/>
        public event TranslationLookupCompletedEventHandler TranslationLookupCompleted;
        
        /// <remarks/>
        public event LanguageListCompletedEventHandler LanguageListCompleted;
        
        /// <remarks/>
        public event LanguageNameQueryByIdCompletedEventHandler LanguageNameQueryByIdCompleted;
        
        /// <remarks/>
        public event UserLanguageListByIdCompletedEventHandler UserLanguageListByIdCompleted;
        
        /// <remarks/>
        public event UserLanguageSetByIdCompletedEventHandler UserLanguageSetByIdCompleted;
        
        /// <remarks/>
        public event UserLanguageDeleteByIdCompletedEventHandler UserLanguageDeleteByIdCompleted;
        
        /// <remarks/>
        public event InterestListCompletedEventHandler InterestListCompleted;
        
        /// <remarks/>
        public event InterestLangListCompletedEventHandler InterestLangListCompleted;
        
        /// <remarks/>
        public event InterestNameQueryByIdCompletedEventHandler InterestNameQueryByIdCompleted;
        
        /// <remarks/>
        public event UserInterestListCompletedEventHandler UserInterestListCompleted;
        
        /// <remarks/>
        public event UserInterestAddByIdCompletedEventHandler UserInterestAddByIdCompleted;
        
        /// <remarks/>
        public event UserInterestDeleteByIdCompletedEventHandler UserInterestDeleteByIdCompleted;
        
        /// <remarks/>
        public event TransAnsRateByIdCompletedEventHandler TransAnsRateByIdCompleted;
        
        /// <remarks/>
        public event MessageSendCompletedEventHandler MessageSendCompleted;
        
        /// <remarks/>
        public event MessageRecvByUserCompletedEventHandler MessageRecvByUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/Initialize", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Initialize() {
            this.Invoke("Initialize", new object[0]);
        }
        
        /// <remarks/>
        public void InitializeAsync() {
            this.InitializeAsync(null);
        }
        
        /// <remarks/>
        public void InitializeAsync(object userState) {
            if ((this.InitializeOperationCompleted == null)) {
                this.InitializeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeOperationCompleted);
            }
            this.InvokeAsync("Initialize", new object[0], this.InitializeOperationCompleted, userState);
        }
        
        private void OnInitializeOperationCompleted(object arg) {
            if ((this.InitializeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserCaptcha", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] UserCaptcha(int width, int height, string bgColor, string frontColor) {
            object[] results = this.Invoke("UserCaptcha", new object[] {
                        width,
                        height,
                        bgColor,
                        frontColor});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void UserCaptchaAsync(int width, int height, string bgColor, string frontColor) {
            this.UserCaptchaAsync(width, height, bgColor, frontColor, null);
        }
        
        /// <remarks/>
        public void UserCaptchaAsync(int width, int height, string bgColor, string frontColor, object userState) {
            if ((this.UserCaptchaOperationCompleted == null)) {
                this.UserCaptchaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserCaptchaOperationCompleted);
            }
            this.InvokeAsync("UserCaptcha", new object[] {
                        width,
                        height,
                        bgColor,
                        frontColor}, this.UserCaptchaOperationCompleted, userState);
        }
        
        private void OnUserCaptchaOperationCompleted(object arg) {
            if ((this.UserCaptchaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserCaptchaCompleted(this, new UserCaptchaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserRegister", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UserRegister(string username, string md5password, string email, string name, string description, string captcha) {
            object[] results = this.Invoke("UserRegister", new object[] {
                        username,
                        md5password,
                        email,
                        name,
                        description,
                        captcha});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UserRegisterAsync(string username, string md5password, string email, string name, string description, string captcha) {
            this.UserRegisterAsync(username, md5password, email, name, description, captcha, null);
        }
        
        /// <remarks/>
        public void UserRegisterAsync(string username, string md5password, string email, string name, string description, string captcha, object userState) {
            if ((this.UserRegisterOperationCompleted == null)) {
                this.UserRegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserRegisterOperationCompleted);
            }
            this.InvokeAsync("UserRegister", new object[] {
                        username,
                        md5password,
                        email,
                        name,
                        description,
                        captcha}, this.UserRegisterOperationCompleted, userState);
        }
        
        private void OnUserRegisterOperationCompleted(object arg) {
            if ((this.UserRegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserRegisterCompleted(this, new UserRegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserAuthorizeByUsername", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User UserAuthorizeByUsername(string username, string md5password) {
            object[] results = this.Invoke("UserAuthorizeByUsername", new object[] {
                        username,
                        md5password});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void UserAuthorizeByUsernameAsync(string username, string md5password) {
            this.UserAuthorizeByUsernameAsync(username, md5password, null);
        }
        
        /// <remarks/>
        public void UserAuthorizeByUsernameAsync(string username, string md5password, object userState) {
            if ((this.UserAuthorizeByUsernameOperationCompleted == null)) {
                this.UserAuthorizeByUsernameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserAuthorizeByUsernameOperationCompleted);
            }
            this.InvokeAsync("UserAuthorizeByUsername", new object[] {
                        username,
                        md5password}, this.UserAuthorizeByUsernameOperationCompleted, userState);
        }
        
        private void OnUserAuthorizeByUsernameOperationCompleted(object arg) {
            if ((this.UserAuthorizeByUsernameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserAuthorizeByUsernameCompleted(this, new UserAuthorizeByUsernameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserIsLoggedIn", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UserIsLoggedIn() {
            object[] results = this.Invoke("UserIsLoggedIn", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UserIsLoggedInAsync() {
            this.UserIsLoggedInAsync(null);
        }
        
        /// <remarks/>
        public void UserIsLoggedInAsync(object userState) {
            if ((this.UserIsLoggedInOperationCompleted == null)) {
                this.UserIsLoggedInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserIsLoggedInOperationCompleted);
            }
            this.InvokeAsync("UserIsLoggedIn", new object[0], this.UserIsLoggedInOperationCompleted, userState);
        }
        
        private void OnUserIsLoggedInOperationCompleted(object arg) {
            if ((this.UserIsLoggedInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserIsLoggedInCompleted(this, new UserIsLoggedInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserLogout", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UserLogout() {
            this.Invoke("UserLogout", new object[0]);
        }
        
        /// <remarks/>
        public void UserLogoutAsync() {
            this.UserLogoutAsync(null);
        }
        
        /// <remarks/>
        public void UserLogoutAsync(object userState) {
            if ((this.UserLogoutOperationCompleted == null)) {
                this.UserLogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserLogoutOperationCompleted);
            }
            this.InvokeAsync("UserLogout", new object[0], this.UserLogoutOperationCompleted, userState);
        }
        
        private void OnUserLogoutOperationCompleted(object arg) {
            if ((this.UserLogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserLogoutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserCurrent", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User UserCurrent() {
            object[] results = this.Invoke("UserCurrent", new object[0]);
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void UserCurrentAsync() {
            this.UserCurrentAsync(null);
        }
        
        /// <remarks/>
        public void UserCurrentAsync(object userState) {
            if ((this.UserCurrentOperationCompleted == null)) {
                this.UserCurrentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserCurrentOperationCompleted);
            }
            this.InvokeAsync("UserCurrent", new object[0], this.UserCurrentOperationCompleted, userState);
        }
        
        private void OnUserCurrentOperationCompleted(object arg) {
            if ((this.UserCurrentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserCurrentCompleted(this, new UserCurrentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserUpdateById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UserUpdateById(int user_id, string email, string name, string description) {
            this.Invoke("UserUpdateById", new object[] {
                        user_id,
                        email,
                        name,
                        description});
        }
        
        /// <remarks/>
        public void UserUpdateByIdAsync(int user_id, string email, string name, string description) {
            this.UserUpdateByIdAsync(user_id, email, name, description, null);
        }
        
        /// <remarks/>
        public void UserUpdateByIdAsync(int user_id, string email, string name, string description, object userState) {
            if ((this.UserUpdateByIdOperationCompleted == null)) {
                this.UserUpdateByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserUpdateByIdOperationCompleted);
            }
            this.InvokeAsync("UserUpdateById", new object[] {
                        user_id,
                        email,
                        name,
                        description}, this.UserUpdateByIdOperationCompleted, userState);
        }
        
        private void OnUserUpdateByIdOperationCompleted(object arg) {
            if ((this.UserUpdateByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserUpdateByIdCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserPasswordUpdate", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UserPasswordUpdate(string oldmd5password, string newmd5password) {
            object[] results = this.Invoke("UserPasswordUpdate", new object[] {
                        oldmd5password,
                        newmd5password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UserPasswordUpdateAsync(string oldmd5password, string newmd5password) {
            this.UserPasswordUpdateAsync(oldmd5password, newmd5password, null);
        }
        
        /// <remarks/>
        public void UserPasswordUpdateAsync(string oldmd5password, string newmd5password, object userState) {
            if ((this.UserPasswordUpdateOperationCompleted == null)) {
                this.UserPasswordUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserPasswordUpdateOperationCompleted);
            }
            this.InvokeAsync("UserPasswordUpdate", new object[] {
                        oldmd5password,
                        newmd5password}, this.UserPasswordUpdateOperationCompleted, userState);
        }
        
        private void OnUserPasswordUpdateOperationCompleted(object arg) {
            if ((this.UserPasswordUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserPasswordUpdateCompleted(this, new UserPasswordUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserIdGetByUsername", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UserIdGetByUsername(string username) {
            object[] results = this.Invoke("UserIdGetByUsername", new object[] {
                        username});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UserIdGetByUsernameAsync(string username) {
            this.UserIdGetByUsernameAsync(username, null);
        }
        
        /// <remarks/>
        public void UserIdGetByUsernameAsync(string username, object userState) {
            if ((this.UserIdGetByUsernameOperationCompleted == null)) {
                this.UserIdGetByUsernameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserIdGetByUsernameOperationCompleted);
            }
            this.InvokeAsync("UserIdGetByUsername", new object[] {
                        username}, this.UserIdGetByUsernameOperationCompleted, userState);
        }
        
        private void OnUserIdGetByUsernameOperationCompleted(object arg) {
            if ((this.UserIdGetByUsernameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserIdGetByUsernameCompleted(this, new UserIdGetByUsernameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/DictionaryLookup", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DictionaryLookup(int LanguageID, string SearchWord) {
            object[] results = this.Invoke("DictionaryLookup", new object[] {
                        LanguageID,
                        SearchWord});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DictionaryLookupAsync(int LanguageID, string SearchWord) {
            this.DictionaryLookupAsync(LanguageID, SearchWord, null);
        }
        
        /// <remarks/>
        public void DictionaryLookupAsync(int LanguageID, string SearchWord, object userState) {
            if ((this.DictionaryLookupOperationCompleted == null)) {
                this.DictionaryLookupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDictionaryLookupOperationCompleted);
            }
            this.InvokeAsync("DictionaryLookup", new object[] {
                        LanguageID,
                        SearchWord}, this.DictionaryLookupOperationCompleted, userState);
        }
        
        private void OnDictionaryLookupOperationCompleted(object arg) {
            if ((this.DictionaryLookupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DictionaryLookupCompleted(this, new DictionaryLookupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/TranslationLookup", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TranslationLookup(int OrigLanguage, int SearchLanguage, string SearchWord) {
            object[] results = this.Invoke("TranslationLookup", new object[] {
                        OrigLanguage,
                        SearchLanguage,
                        SearchWord});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TranslationLookupAsync(int OrigLanguage, int SearchLanguage, string SearchWord) {
            this.TranslationLookupAsync(OrigLanguage, SearchLanguage, SearchWord, null);
        }
        
        /// <remarks/>
        public void TranslationLookupAsync(int OrigLanguage, int SearchLanguage, string SearchWord, object userState) {
            if ((this.TranslationLookupOperationCompleted == null)) {
                this.TranslationLookupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTranslationLookupOperationCompleted);
            }
            this.InvokeAsync("TranslationLookup", new object[] {
                        OrigLanguage,
                        SearchLanguage,
                        SearchWord}, this.TranslationLookupOperationCompleted, userState);
        }
        
        private void OnTranslationLookupOperationCompleted(object arg) {
            if ((this.TranslationLookupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TranslationLookupCompleted(this, new TranslationLookupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/LanguageList", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Language[] LanguageList() {
            object[] results = this.Invoke("LanguageList", new object[0]);
            return ((Language[])(results[0]));
        }
        
        /// <remarks/>
        public void LanguageListAsync() {
            this.LanguageListAsync(null);
        }
        
        /// <remarks/>
        public void LanguageListAsync(object userState) {
            if ((this.LanguageListOperationCompleted == null)) {
                this.LanguageListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLanguageListOperationCompleted);
            }
            this.InvokeAsync("LanguageList", new object[0], this.LanguageListOperationCompleted, userState);
        }
        
        private void OnLanguageListOperationCompleted(object arg) {
            if ((this.LanguageListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LanguageListCompleted(this, new LanguageListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/LanguageNameQueryById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LanguageNameQueryById(int lang_id, int dst_lang_id) {
            object[] results = this.Invoke("LanguageNameQueryById", new object[] {
                        lang_id,
                        dst_lang_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LanguageNameQueryByIdAsync(int lang_id, int dst_lang_id) {
            this.LanguageNameQueryByIdAsync(lang_id, dst_lang_id, null);
        }
        
        /// <remarks/>
        public void LanguageNameQueryByIdAsync(int lang_id, int dst_lang_id, object userState) {
            if ((this.LanguageNameQueryByIdOperationCompleted == null)) {
                this.LanguageNameQueryByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLanguageNameQueryByIdOperationCompleted);
            }
            this.InvokeAsync("LanguageNameQueryById", new object[] {
                        lang_id,
                        dst_lang_id}, this.LanguageNameQueryByIdOperationCompleted, userState);
        }
        
        private void OnLanguageNameQueryByIdOperationCompleted(object arg) {
            if ((this.LanguageNameQueryByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LanguageNameQueryByIdCompleted(this, new LanguageNameQueryByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserLanguageListById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserLanguage[] UserLanguageListById(int user_id) {
            object[] results = this.Invoke("UserLanguageListById", new object[] {
                        user_id});
            return ((UserLanguage[])(results[0]));
        }
        
        /// <remarks/>
        public void UserLanguageListByIdAsync(int user_id) {
            this.UserLanguageListByIdAsync(user_id, null);
        }
        
        /// <remarks/>
        public void UserLanguageListByIdAsync(int user_id, object userState) {
            if ((this.UserLanguageListByIdOperationCompleted == null)) {
                this.UserLanguageListByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserLanguageListByIdOperationCompleted);
            }
            this.InvokeAsync("UserLanguageListById", new object[] {
                        user_id}, this.UserLanguageListByIdOperationCompleted, userState);
        }
        
        private void OnUserLanguageListByIdOperationCompleted(object arg) {
            if ((this.UserLanguageListByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserLanguageListByIdCompleted(this, new UserLanguageListByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserLanguageSetById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UserLanguageSetById(int user_id, short lang_id, short self_rating) {
            this.Invoke("UserLanguageSetById", new object[] {
                        user_id,
                        lang_id,
                        self_rating});
        }
        
        /// <remarks/>
        public void UserLanguageSetByIdAsync(int user_id, short lang_id, short self_rating) {
            this.UserLanguageSetByIdAsync(user_id, lang_id, self_rating, null);
        }
        
        /// <remarks/>
        public void UserLanguageSetByIdAsync(int user_id, short lang_id, short self_rating, object userState) {
            if ((this.UserLanguageSetByIdOperationCompleted == null)) {
                this.UserLanguageSetByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserLanguageSetByIdOperationCompleted);
            }
            this.InvokeAsync("UserLanguageSetById", new object[] {
                        user_id,
                        lang_id,
                        self_rating}, this.UserLanguageSetByIdOperationCompleted, userState);
        }
        
        private void OnUserLanguageSetByIdOperationCompleted(object arg) {
            if ((this.UserLanguageSetByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserLanguageSetByIdCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserLanguageDeleteById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UserLanguageDeleteById(int user_id, short lang_id) {
            this.Invoke("UserLanguageDeleteById", new object[] {
                        user_id,
                        lang_id});
        }
        
        /// <remarks/>
        public void UserLanguageDeleteByIdAsync(int user_id, short lang_id) {
            this.UserLanguageDeleteByIdAsync(user_id, lang_id, null);
        }
        
        /// <remarks/>
        public void UserLanguageDeleteByIdAsync(int user_id, short lang_id, object userState) {
            if ((this.UserLanguageDeleteByIdOperationCompleted == null)) {
                this.UserLanguageDeleteByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserLanguageDeleteByIdOperationCompleted);
            }
            this.InvokeAsync("UserLanguageDeleteById", new object[] {
                        user_id,
                        lang_id}, this.UserLanguageDeleteByIdOperationCompleted, userState);
        }
        
        private void OnUserLanguageDeleteByIdOperationCompleted(object arg) {
            if ((this.UserLanguageDeleteByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserLanguageDeleteByIdCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/InterestList", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Interest[] InterestList(int parent_id) {
            object[] results = this.Invoke("InterestList", new object[] {
                        parent_id});
            return ((Interest[])(results[0]));
        }
        
        /// <remarks/>
        public void InterestListAsync(int parent_id) {
            this.InterestListAsync(parent_id, null);
        }
        
        /// <remarks/>
        public void InterestListAsync(int parent_id, object userState) {
            if ((this.InterestListOperationCompleted == null)) {
                this.InterestListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInterestListOperationCompleted);
            }
            this.InvokeAsync("InterestList", new object[] {
                        parent_id}, this.InterestListOperationCompleted, userState);
        }
        
        private void OnInterestListOperationCompleted(object arg) {
            if ((this.InterestListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InterestListCompleted(this, new InterestListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/InterestLangList", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Interest[] InterestLangList(int parent_id, int lang_id) {
            object[] results = this.Invoke("InterestLangList", new object[] {
                        parent_id,
                        lang_id});
            return ((Interest[])(results[0]));
        }
        
        /// <remarks/>
        public void InterestLangListAsync(int parent_id, int lang_id) {
            this.InterestLangListAsync(parent_id, lang_id, null);
        }
        
        /// <remarks/>
        public void InterestLangListAsync(int parent_id, int lang_id, object userState) {
            if ((this.InterestLangListOperationCompleted == null)) {
                this.InterestLangListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInterestLangListOperationCompleted);
            }
            this.InvokeAsync("InterestLangList", new object[] {
                        parent_id,
                        lang_id}, this.InterestLangListOperationCompleted, userState);
        }
        
        private void OnInterestLangListOperationCompleted(object arg) {
            if ((this.InterestLangListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InterestLangListCompleted(this, new InterestLangListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/InterestNameQueryById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InterestNameQueryById(int interest_id, int lang_id) {
            object[] results = this.Invoke("InterestNameQueryById", new object[] {
                        interest_id,
                        lang_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InterestNameQueryByIdAsync(int interest_id, int lang_id) {
            this.InterestNameQueryByIdAsync(interest_id, lang_id, null);
        }
        
        /// <remarks/>
        public void InterestNameQueryByIdAsync(int interest_id, int lang_id, object userState) {
            if ((this.InterestNameQueryByIdOperationCompleted == null)) {
                this.InterestNameQueryByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInterestNameQueryByIdOperationCompleted);
            }
            this.InvokeAsync("InterestNameQueryById", new object[] {
                        interest_id,
                        lang_id}, this.InterestNameQueryByIdOperationCompleted, userState);
        }
        
        private void OnInterestNameQueryByIdOperationCompleted(object arg) {
            if ((this.InterestNameQueryByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InterestNameQueryByIdCompleted(this, new InterestNameQueryByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserInterestList", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Interest[] UserInterestList(int user_id) {
            object[] results = this.Invoke("UserInterestList", new object[] {
                        user_id});
            return ((Interest[])(results[0]));
        }
        
        /// <remarks/>
        public void UserInterestListAsync(int user_id) {
            this.UserInterestListAsync(user_id, null);
        }
        
        /// <remarks/>
        public void UserInterestListAsync(int user_id, object userState) {
            if ((this.UserInterestListOperationCompleted == null)) {
                this.UserInterestListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserInterestListOperationCompleted);
            }
            this.InvokeAsync("UserInterestList", new object[] {
                        user_id}, this.UserInterestListOperationCompleted, userState);
        }
        
        private void OnUserInterestListOperationCompleted(object arg) {
            if ((this.UserInterestListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserInterestListCompleted(this, new UserInterestListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserInterestAddById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UserInterestAddById(int user_id, int interest_id) {
            this.Invoke("UserInterestAddById", new object[] {
                        user_id,
                        interest_id});
        }
        
        /// <remarks/>
        public void UserInterestAddByIdAsync(int user_id, int interest_id) {
            this.UserInterestAddByIdAsync(user_id, interest_id, null);
        }
        
        /// <remarks/>
        public void UserInterestAddByIdAsync(int user_id, int interest_id, object userState) {
            if ((this.UserInterestAddByIdOperationCompleted == null)) {
                this.UserInterestAddByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserInterestAddByIdOperationCompleted);
            }
            this.InvokeAsync("UserInterestAddById", new object[] {
                        user_id,
                        interest_id}, this.UserInterestAddByIdOperationCompleted, userState);
        }
        
        private void OnUserInterestAddByIdOperationCompleted(object arg) {
            if ((this.UserInterestAddByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserInterestAddByIdCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserInterestDeleteById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UserInterestDeleteById(int user_id, int interest_id) {
            this.Invoke("UserInterestDeleteById", new object[] {
                        user_id,
                        interest_id});
        }
        
        /// <remarks/>
        public void UserInterestDeleteByIdAsync(int user_id, int interest_id) {
            this.UserInterestDeleteByIdAsync(user_id, interest_id, null);
        }
        
        /// <remarks/>
        public void UserInterestDeleteByIdAsync(int user_id, int interest_id, object userState) {
            if ((this.UserInterestDeleteByIdOperationCompleted == null)) {
                this.UserInterestDeleteByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserInterestDeleteByIdOperationCompleted);
            }
            this.InvokeAsync("UserInterestDeleteById", new object[] {
                        user_id,
                        interest_id}, this.UserInterestDeleteByIdOperationCompleted, userState);
        }
        
        private void OnUserInterestDeleteByIdOperationCompleted(object arg) {
            if ((this.UserInterestDeleteByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserInterestDeleteByIdCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/TransAnsRateById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TransAnsRateById(int user_id, int trans_ans_id, short rating) {
            this.Invoke("TransAnsRateById", new object[] {
                        user_id,
                        trans_ans_id,
                        rating});
        }
        
        /// <remarks/>
        public void TransAnsRateByIdAsync(int user_id, int trans_ans_id, short rating) {
            this.TransAnsRateByIdAsync(user_id, trans_ans_id, rating, null);
        }
        
        /// <remarks/>
        public void TransAnsRateByIdAsync(int user_id, int trans_ans_id, short rating, object userState) {
            if ((this.TransAnsRateByIdOperationCompleted == null)) {
                this.TransAnsRateByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransAnsRateByIdOperationCompleted);
            }
            this.InvokeAsync("TransAnsRateById", new object[] {
                        user_id,
                        trans_ans_id,
                        rating}, this.TransAnsRateByIdOperationCompleted, userState);
        }
        
        private void OnTransAnsRateByIdOperationCompleted(object arg) {
            if ((this.TransAnsRateByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransAnsRateByIdCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/MessageSend", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MessageSend(int user_id, int dst_id, MessageDestinationType dst_type, string subject, string body) {
            this.Invoke("MessageSend", new object[] {
                        user_id,
                        dst_id,
                        dst_type,
                        subject,
                        body});
        }
        
        /// <remarks/>
        public void MessageSendAsync(int user_id, int dst_id, MessageDestinationType dst_type, string subject, string body) {
            this.MessageSendAsync(user_id, dst_id, dst_type, subject, body, null);
        }
        
        /// <remarks/>
        public void MessageSendAsync(int user_id, int dst_id, MessageDestinationType dst_type, string subject, string body, object userState) {
            if ((this.MessageSendOperationCompleted == null)) {
                this.MessageSendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMessageSendOperationCompleted);
            }
            this.InvokeAsync("MessageSend", new object[] {
                        user_id,
                        dst_id,
                        dst_type,
                        subject,
                        body}, this.MessageSendOperationCompleted, userState);
        }
        
        private void OnMessageSendOperationCompleted(object arg) {
            if ((this.MessageSendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MessageSendCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/MessageRecvByUser", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Message[] MessageRecvByUser(int dst_id, MessageDestinationType dst_type) {
            object[] results = this.Invoke("MessageRecvByUser", new object[] {
                        dst_id,
                        dst_type});
            return ((Message[])(results[0]));
        }
        
        /// <remarks/>
        public void MessageRecvByUserAsync(int dst_id, MessageDestinationType dst_type) {
            this.MessageRecvByUserAsync(dst_id, dst_type, null);
        }
        
        /// <remarks/>
        public void MessageRecvByUserAsync(int dst_id, MessageDestinationType dst_type, object userState) {
            if ((this.MessageRecvByUserOperationCompleted == null)) {
                this.MessageRecvByUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMessageRecvByUserOperationCompleted);
            }
            this.InvokeAsync("MessageRecvByUser", new object[] {
                        dst_id,
                        dst_type}, this.MessageRecvByUserOperationCompleted, userState);
        }
        
        private void OnMessageRecvByUserOperationCompleted(object arg) {
            if ((this.MessageRecvByUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MessageRecvByUserCompleted(this, new MessageRecvByUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniproject.org/")]
    public partial class User {
        
        private string nameField;
        
        private string usernameField;
        
        private string emailField;
        
        private int idField;
        
        private string descriptionField;
        
        private System.DateTime reg_dateField;
        
        private System.DateTime log_dateField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime reg_date {
            get {
                return this.reg_dateField;
            }
            set {
                this.reg_dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime log_date {
            get {
                return this.log_dateField;
            }
            set {
                this.log_dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniproject.org/")]
    public partial class Message {
        
        private int src_idField;
        
        private int dst_idField;
        
        private string subjectField;
        
        private string bodyField;
        
        private System.DateTime dateField;
        
        private bool unreadField;
        
        /// <remarks/>
        public int src_id {
            get {
                return this.src_idField;
            }
            set {
                this.src_idField = value;
            }
        }
        
        /// <remarks/>
        public int dst_id {
            get {
                return this.dst_idField;
            }
            set {
                this.dst_idField = value;
            }
        }
        
        /// <remarks/>
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public bool unread {
            get {
                return this.unreadField;
            }
            set {
                this.unreadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniproject.org/")]
    public partial class Interest {
        
        private int idField;
        
        private int parent_idField;
        
        private string nameField;
        
        private int lang_idField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int parent_id {
            get {
                return this.parent_idField;
            }
            set {
                this.parent_idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int lang_id {
            get {
                return this.lang_idField;
            }
            set {
                this.lang_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniproject.org/")]
    public partial class UserLanguage {
        
        private int lang_idField;
        
        private int user_idField;
        
        private short net_ratingField;
        
        private short self_ratingField;
        
        /// <remarks/>
        public int lang_id {
            get {
                return this.lang_idField;
            }
            set {
                this.lang_idField = value;
            }
        }
        
        /// <remarks/>
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
            }
        }
        
        /// <remarks/>
        public short net_rating {
            get {
                return this.net_ratingField;
            }
            set {
                this.net_ratingField = value;
            }
        }
        
        /// <remarks/>
        public short self_rating {
            get {
                return this.self_ratingField;
            }
            set {
                this.self_ratingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniproject.org/")]
    public partial class Language {
        
        private int idField;
        
        private string codeField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniproject.org/")]
    public enum MessageDestinationType {
        
        /// <remarks/>
        User,
        
        /// <remarks/>
        Group,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void InitializeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserCaptchaCompletedEventHandler(object sender, UserCaptchaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserCaptchaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserCaptchaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserRegisterCompletedEventHandler(object sender, UserRegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserRegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserRegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserAuthorizeByUsernameCompletedEventHandler(object sender, UserAuthorizeByUsernameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserAuthorizeByUsernameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserAuthorizeByUsernameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserIsLoggedInCompletedEventHandler(object sender, UserIsLoggedInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserIsLoggedInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserIsLoggedInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserLogoutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserCurrentCompletedEventHandler(object sender, UserCurrentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserCurrentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserCurrentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserUpdateByIdCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserPasswordUpdateCompletedEventHandler(object sender, UserPasswordUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserPasswordUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserPasswordUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserIdGetByUsernameCompletedEventHandler(object sender, UserIdGetByUsernameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserIdGetByUsernameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserIdGetByUsernameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void DictionaryLookupCompletedEventHandler(object sender, DictionaryLookupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DictionaryLookupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DictionaryLookupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void TranslationLookupCompletedEventHandler(object sender, TranslationLookupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TranslationLookupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TranslationLookupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void LanguageListCompletedEventHandler(object sender, LanguageListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LanguageListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LanguageListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Language[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Language[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void LanguageNameQueryByIdCompletedEventHandler(object sender, LanguageNameQueryByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LanguageNameQueryByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LanguageNameQueryByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserLanguageListByIdCompletedEventHandler(object sender, UserLanguageListByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserLanguageListByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserLanguageListByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserLanguage[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserLanguage[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserLanguageSetByIdCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserLanguageDeleteByIdCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void InterestListCompletedEventHandler(object sender, InterestListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InterestListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InterestListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Interest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Interest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void InterestLangListCompletedEventHandler(object sender, InterestLangListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InterestLangListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InterestLangListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Interest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Interest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void InterestNameQueryByIdCompletedEventHandler(object sender, InterestNameQueryByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InterestNameQueryByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InterestNameQueryByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserInterestListCompletedEventHandler(object sender, UserInterestListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserInterestListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserInterestListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Interest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Interest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserInterestAddByIdCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void UserInterestDeleteByIdCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void TransAnsRateByIdCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void MessageSendCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void MessageRecvByUserCompletedEventHandler(object sender, MessageRecvByUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessageRecvByUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MessageRecvByUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Message[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Message[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591