//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.312.
// 
namespace Omni.Pocket.org.omniproject {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://omniproject.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WebService() {
            this.Url = "http://omniproject.org/Service/WebService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/Initialize", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Initialize() {
            this.Invoke("Initialize", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInitialize(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Initialize", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndInitialize(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserCaptcha", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] UserCaptcha(int width, int height, string bgColor, string frontColor) {
            object[] results = this.Invoke("UserCaptcha", new object[] {
                        width,
                        height,
                        bgColor,
                        frontColor});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserCaptcha(int width, int height, string bgColor, string frontColor, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserCaptcha", new object[] {
                        width,
                        height,
                        bgColor,
                        frontColor}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndUserCaptcha(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserRegister", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UserRegister(string username, string md5password, string email, string name, string description, string captcha) {
            object[] results = this.Invoke("UserRegister", new object[] {
                        username,
                        md5password,
                        email,
                        name,
                        description,
                        captcha});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserRegister(string username, string md5password, string email, string name, string description, string captcha, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserRegister", new object[] {
                        username,
                        md5password,
                        email,
                        name,
                        description,
                        captcha}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndUserRegister(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserAuthorizeByUsername", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User UserAuthorizeByUsername(string username, string md5password) {
            object[] results = this.Invoke("UserAuthorizeByUsername", new object[] {
                        username,
                        md5password});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserAuthorizeByUsername(string username, string md5password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserAuthorizeByUsername", new object[] {
                        username,
                        md5password}, callback, asyncState);
        }
        
        /// <remarks/>
        public User EndUserAuthorizeByUsername(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserIsLoggedIn", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UserIsLoggedIn() {
            object[] results = this.Invoke("UserIsLoggedIn", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserIsLoggedIn(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserIsLoggedIn", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndUserIsLoggedIn(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserLogout", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UserLogout() {
            this.Invoke("UserLogout", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserLogout(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserLogout", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUserLogout(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserCurrent", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User UserCurrent() {
            object[] results = this.Invoke("UserCurrent", new object[0]);
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserCurrent(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserCurrent", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public User EndUserCurrent(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserUpdateById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UserUpdateById(int user_id, string email, string name, string description) {
            this.Invoke("UserUpdateById", new object[] {
                        user_id,
                        email,
                        name,
                        description});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserUpdateById(int user_id, string email, string name, string description, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserUpdateById", new object[] {
                        user_id,
                        email,
                        name,
                        description}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUserUpdateById(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserGetById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User UserGetById(int user_id) {
            object[] results = this.Invoke("UserGetById", new object[] {
                        user_id});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserGetById(int user_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserGetById", new object[] {
                        user_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public User EndUserGetById(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserPasswordUpdate", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UserPasswordUpdate(string oldmd5password, string newmd5password) {
            object[] results = this.Invoke("UserPasswordUpdate", new object[] {
                        oldmd5password,
                        newmd5password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserPasswordUpdate(string oldmd5password, string newmd5password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserPasswordUpdate", new object[] {
                        oldmd5password,
                        newmd5password}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndUserPasswordUpdate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserIdGetByUsername", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UserIdGetByUsername(string username) {
            object[] results = this.Invoke("UserIdGetByUsername", new object[] {
                        username});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserIdGetByUsername(string username, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserIdGetByUsername", new object[] {
                        username}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndUserIdGetByUsername(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/DictionaryLookup", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DictionaryLookup(int LanguageID, string SearchWord) {
            object[] results = this.Invoke("DictionaryLookup", new object[] {
                        LanguageID,
                        SearchWord});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDictionaryLookup(int LanguageID, string SearchWord, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DictionaryLookup", new object[] {
                        LanguageID,
                        SearchWord}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndDictionaryLookup(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/TranslationLookup", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TranslationLookup(int OrigLanguage, int SearchLanguage, string SearchWord) {
            object[] results = this.Invoke("TranslationLookup", new object[] {
                        OrigLanguage,
                        SearchLanguage,
                        SearchWord});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTranslationLookup(int OrigLanguage, int SearchLanguage, string SearchWord, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TranslationLookup", new object[] {
                        OrigLanguage,
                        SearchLanguage,
                        SearchWord}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndTranslationLookup(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/LanguageList", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Language[] LanguageList() {
            object[] results = this.Invoke("LanguageList", new object[0]);
            return ((Language[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLanguageList(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LanguageList", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public Language[] EndLanguageList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Language[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/LanguageNameQueryById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LanguageNameQueryById(int lang_id, int dst_lang_id) {
            object[] results = this.Invoke("LanguageNameQueryById", new object[] {
                        lang_id,
                        dst_lang_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLanguageNameQueryById(int lang_id, int dst_lang_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LanguageNameQueryById", new object[] {
                        lang_id,
                        dst_lang_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndLanguageNameQueryById(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserLanguageListById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserLanguage[] UserLanguageListById(int user_id) {
            object[] results = this.Invoke("UserLanguageListById", new object[] {
                        user_id});
            return ((UserLanguage[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserLanguageListById(int user_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserLanguageListById", new object[] {
                        user_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public UserLanguage[] EndUserLanguageListById(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UserLanguage[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserLanguageSetById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UserLanguageSetById(int user_id, int lang_id, short self_rating) {
            this.Invoke("UserLanguageSetById", new object[] {
                        user_id,
                        lang_id,
                        self_rating});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserLanguageSetById(int user_id, int lang_id, short self_rating, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserLanguageSetById", new object[] {
                        user_id,
                        lang_id,
                        self_rating}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUserLanguageSetById(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserLanguageDeleteById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UserLanguageDeleteById(int user_id, int lang_id) {
            this.Invoke("UserLanguageDeleteById", new object[] {
                        user_id,
                        lang_id});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserLanguageDeleteById(int user_id, int lang_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserLanguageDeleteById", new object[] {
                        user_id,
                        lang_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUserLanguageDeleteById(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/InterestList", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Interest[] InterestList(int parent_id) {
            object[] results = this.Invoke("InterestList", new object[] {
                        parent_id});
            return ((Interest[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInterestList(int parent_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InterestList", new object[] {
                        parent_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public Interest[] EndInterestList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Interest[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/InterestLangList", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Interest[] InterestLangList(int parent_id, int lang_id) {
            object[] results = this.Invoke("InterestLangList", new object[] {
                        parent_id,
                        lang_id});
            return ((Interest[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInterestLangList(int parent_id, int lang_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InterestLangList", new object[] {
                        parent_id,
                        lang_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public Interest[] EndInterestLangList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Interest[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/InterestNameQueryById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InterestNameQueryById(int interest_id, int lang_id) {
            object[] results = this.Invoke("InterestNameQueryById", new object[] {
                        interest_id,
                        lang_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInterestNameQueryById(int interest_id, int lang_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InterestNameQueryById", new object[] {
                        interest_id,
                        lang_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInterestNameQueryById(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserInterestList", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Interest[] UserInterestList(int user_id) {
            object[] results = this.Invoke("UserInterestList", new object[] {
                        user_id});
            return ((Interest[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserInterestList(int user_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserInterestList", new object[] {
                        user_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public Interest[] EndUserInterestList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Interest[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserInterestAddById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UserInterestAddById(int user_id, int interest_id) {
            this.Invoke("UserInterestAddById", new object[] {
                        user_id,
                        interest_id});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserInterestAddById(int user_id, int interest_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserInterestAddById", new object[] {
                        user_id,
                        interest_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUserInterestAddById(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/UserInterestDeleteById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UserInterestDeleteById(int user_id, int interest_id) {
            this.Invoke("UserInterestDeleteById", new object[] {
                        user_id,
                        interest_id});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserInterestDeleteById(int user_id, int interest_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserInterestDeleteById", new object[] {
                        user_id,
                        interest_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUserInterestDeleteById(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/TransAnsRateById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TransAnsRateById(int user_id, int trans_ans_id, short rating) {
            this.Invoke("TransAnsRateById", new object[] {
                        user_id,
                        trans_ans_id,
                        rating});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTransAnsRateById(int user_id, int trans_ans_id, short rating, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TransAnsRateById", new object[] {
                        user_id,
                        trans_ans_id,
                        rating}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndTransAnsRateById(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/MessageSend", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MessageSend(int user_id, int dst_id, MessageDestinationType dst_type, string subject, string body) {
            this.Invoke("MessageSend", new object[] {
                        user_id,
                        dst_id,
                        dst_type,
                        subject,
                        body});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginMessageSend(int user_id, int dst_id, MessageDestinationType dst_type, string subject, string body, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("MessageSend", new object[] {
                        user_id,
                        dst_id,
                        dst_type,
                        subject,
                        body}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndMessageSend(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/MessageRecvByUser", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Message[] MessageRecvByUser(int dst_id, MessageDestinationType dst_type) {
            object[] results = this.Invoke("MessageRecvByUser", new object[] {
                        dst_id,
                        dst_type});
            return ((Message[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginMessageRecvByUser(int dst_id, MessageDestinationType dst_type, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("MessageRecvByUser", new object[] {
                        dst_id,
                        dst_type}, callback, asyncState);
        }
        
        /// <remarks/>
        public Message[] EndMessageRecvByUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Message[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/MessageSentByUser", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Message[] MessageSentByUser(int user_id) {
            object[] results = this.Invoke("MessageSentByUser", new object[] {
                        user_id});
            return ((Message[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginMessageSentByUser(int user_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("MessageSentByUser", new object[] {
                        user_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public Message[] EndMessageSentByUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Message[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://omniproject.org/MessageGetById", RequestNamespace="http://omniproject.org/", ResponseNamespace="http://omniproject.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Message MessageGetById(int msg_id) {
            object[] results = this.Invoke("MessageGetById", new object[] {
                        msg_id});
            return ((Message)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginMessageGetById(int msg_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("MessageGetById", new object[] {
                        msg_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public Message EndMessageGetById(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Message)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniproject.org/")]
    public partial class User {
        
        private string nameField;
        
        private string usernameField;
        
        private string emailField;
        
        private int idField;
        
        private string descriptionField;
        
        private System.DateTime reg_dateField;
        
        private System.DateTime log_dateField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime reg_date {
            get {
                return this.reg_dateField;
            }
            set {
                this.reg_dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime log_date {
            get {
                return this.log_dateField;
            }
            set {
                this.log_dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniproject.org/")]
    public partial class Message {
        
        private int idField;
        
        private int src_idField;
        
        private int dst_idField;
        
        private string subjectField;
        
        private string bodyField;
        
        private System.DateTime dateField;
        
        private bool unreadField;
        
        private bool pending_transField;
        
        private MessageDestinationType dst_typeField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int src_id {
            get {
                return this.src_idField;
            }
            set {
                this.src_idField = value;
            }
        }
        
        /// <remarks/>
        public int dst_id {
            get {
                return this.dst_idField;
            }
            set {
                this.dst_idField = value;
            }
        }
        
        /// <remarks/>
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public bool unread {
            get {
                return this.unreadField;
            }
            set {
                this.unreadField = value;
            }
        }
        
        /// <remarks/>
        public bool pending_trans {
            get {
                return this.pending_transField;
            }
            set {
                this.pending_transField = value;
            }
        }
        
        /// <remarks/>
        public MessageDestinationType dst_type {
            get {
                return this.dst_typeField;
            }
            set {
                this.dst_typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniproject.org/")]
    public enum MessageDestinationType {
        
        /// <remarks/>
        User,
        
        /// <remarks/>
        Group,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniproject.org/")]
    public partial class Interest {
        
        private int idField;
        
        private int parent_idField;
        
        private string nameField;
        
        private int lang_idField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int parent_id {
            get {
                return this.parent_idField;
            }
            set {
                this.parent_idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int lang_id {
            get {
                return this.lang_idField;
            }
            set {
                this.lang_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniproject.org/")]
    public partial class UserLanguage {
        
        private int lang_idField;
        
        private int user_idField;
        
        private short net_ratingField;
        
        private short self_ratingField;
        
        /// <remarks/>
        public int lang_id {
            get {
                return this.lang_idField;
            }
            set {
                this.lang_idField = value;
            }
        }
        
        /// <remarks/>
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
            }
        }
        
        /// <remarks/>
        public short net_rating {
            get {
                return this.net_ratingField;
            }
            set {
                this.net_ratingField = value;
            }
        }
        
        /// <remarks/>
        public short self_rating {
            get {
                return this.self_ratingField;
            }
            set {
                this.self_ratingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://omniproject.org/")]
    public partial class Language {
        
        private int idField;
        
        private string codeField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
}
